#!/usr/bin/env bash
# A bash script that displays Best School 10 times
# But displays Hi at the 9th iteration
while ((i < 10))
do
  if [ $i -eq 9 ]
  then
   echo "Hi"
  fi
  echo "Best School"
  ((i++))
done
